# Generated by Django 4.0.1 on 2022-01-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='type',
            field=models.CharField(choices=[('triangle', 'triangle'), ('rectangle', 'rectangle'), ('square', 'square'), ('diamond', 'diamond')], default='triangle', max_length=20),
        ),
    ]
