# Generated by Django 4.0.1 on 2022-01-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shape_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='type',
            field=models.CharField(choices=[('triangle', 'triangle'), ('rectangle', 'rectangle'), ('square', 'square'), ('diamond', 'diamond')], max_length=20),
        ),
    ]
